name: Email Sender #TODO Edit the .env

on:
  schedule:
    - cron: '0 */12 * * *'

env:
  DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
  FORM_WEBHOOK: ${{ secrets.FORM_WEBHOOK }}
  FTP_HOST: ${{ secrets.FTP_HOST }}
  FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
  FTP_USER: ${{ secrets.FTP_USER }}
  GOOGLE_CAPTCHA_KEY: ${{ secrets.GOOGLE_CAPTCHA_KEY }}
  MAIL_DEFAULT_SENDER: ${{ secrets.MAIL_DEFAULT_SENDER }}
  MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
  MAIL_PORT: ${{ secrets.MAIL_PORT }}
  MAIL_SERVER: ${{ secrets.MAIL_SERVER }}
  MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
  MAIL_USE_SSL: ${{ secrets.MAIL_USE_SSL }}
  MAIL_USE_TLS: ${{ secrets.MAIL_USE_TLS }}
  MONGO_DATABASE: ${{ secrets.MONGO_DATABASE }}
  MONGO_URI: ${{ secrets.MONGO_URI }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  SUMMARIZATION_API_KEY: ${{ secrets.SUMMARIZATION_API_KEY }}
  SUMMARIZATION_API_KEY_2: ${{ secrets.SUMMARIZATION_API_KEY_2 }}
  WRITER_WEBHOOK: ${{ secrets.WRITER_WEBHOOK }}


jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Send the emails
        run: |
          python -m flask --app gmt commands summarize-news