name: Email Sender

on: workflow_dispatch

env:
  DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
  MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
  MAIL_PORT: ${{ secrets.MAIL_PORT }}
  MAIL_SERVER: ${{ secrets.MAIL_SERVER }}
  MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
  MAIL_USE_SSL: ${{ secrets.MAIL_USE_SSL }}
  MAIL_USE_TLS: ${{ secrets.MAIL_USE_TLS }}
  MONGO_DATABASE: ${{ secrets.MONGO_DATABASE }}
  MONGO_URI: ${{ secrets.MONGO_URI }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}

jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Send the emails
        run: |
          python -m flask --app gmt commands send-emails
